# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sreeharinath Rangaraju
title: IT Infrastructure, DevOps and SRE Consultant
email: gleanup.adm01@gmail.com
website: https://sreeharinathrangaraju.github.io/Profile/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: facespics
github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jameswgrant
linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm an IT Consultant with 20+ years of experience in IT Infrastructure Management, DevOps and SRE. As well as passionate in digital transformation and automation.
  I am most skilled in <mark> Enterprise level technical IT Systems architecture design </mark>, <mark> IT Systems Implemetation and Production support.
  I strongly believe in right action with optimal technical resources empowers an Industry or Business.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: DevOps Implementation for Hudsons Bays Digital Platform
        link: https://www.thebay.com
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Frequent releases and early time to market.
        description: | # this will include new lines to allow paragraphs
          I have Designed and implemented the CICD solutions via git actions for the ecommerce platform.
          Platform engineering design for SRE objectives.
          Automated functional and performance testing via git actions.
          Implemented a scalable containerized solution for multiple microservices.
          Reduced the overall infrastructure cost and license cost by migrating to opensource platforms.
          e.g.: Jenkins to Git actions, Newrelic to Grafana Loki Migration.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Infosys Technologies.
        link: www.Infosys.com        
        sub_title: DevOps and Cloud Consulting
        quote: >
          Strong experience with multiple domain like banking and telecom domain.
        description:
        Client - Ally Bank Technology Labs
        Enabling Dynamic Cloud based DevOps solutions for Financial technology Labs applications, research and proof of concepts.
        Migration Planning and Execution of application to AWS and Open Shift.
        Infrastructure as code in Terraform and Pipeline as code in Gitlab.
        Cloud Architecture Design for applications.
        Client - T-Mobile
        Architecting solutions for DevOps design and implementation for Hadoop and Teradata portfolios.
        Enabling automation for delivering BigData and Data warehouse objects via Continous Integrations and Continous Delivery.
        Played a key role in enabling SOX compliance for true DevOps with appropriate automation, monitoring and reporting.
       
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Anna University 
        caption: 2001 - 2005
        sub_title: BE Computer Science and Engineering 
        quote: >
          Coimbatore Institute of Engineering and Technology.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Information Technology some of my other interests and hobbies are:
      - Meditation and Yoga
      - Passionate in affordable cars
      - Trekking.      
      - Volunteer for World Peace and being better human.
      - Music


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
